FROM node:13

ENV SERVER_BASE=relative
WORKDIR /usr/src/app
RUN chmod -R o+rwx /usr/src/app

COPY package.json package-lock.json ./
RUN npm ci

COPY src/ ./src
COPY dist ./dist
COPY tslint.json tsconfig.json tsconfig.ui.json ./

ENTRYPOINT [ "npm", "run" ]
