# kubectl apply -f k8s.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: siop
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: siop-ingress
  namespace: siop
spec:
  rules:
  - host: sansdid.c19.cards
    http:
      paths:
      - backend:
          serviceName: siop-sansdid
          servicePort: 80
        path: /(.*)
  - host: dev.c19.cards
    http:
      paths:
      - backend:
          serviceName: siop-dev
          servicePort: 80
        path: /(.*)
  - host: c19.cards
    http:
      paths:
      - backend:
          serviceName: siop
          servicePort: 80
        path: /(.*)
  tls:
  - hosts:
    - c19.cards
    - dev.c19.cards
    - sansdid.c19.cards
    secretName: tls-secret
status:
  loadBalancer:
    ingress:
    - {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: siop
  name: siop
spec:
  selector:
    app: siop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siop
  namespace: siop
  labels:
    app: siop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siop
  template:
    metadata:
      labels:
        app: siop
    spec:
      volumes:
      containers:
      - name: ui
        image: argonautcontainerregistry.azurecr.io/siop:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_BASE
          value: "https://c19.cards/api"
---
apiVersion: v1
kind: Service
metadata:
  namespace: siop
  name: siop-dev
spec:
  selector:
    app: siop-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: siop
  name: siop-dev
  labels:
    app: siop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siop-dev
  template:
    metadata:
      labels:
        app: siop-dev
    spec:
      volumes:
      containers:
      - name: ui-dev
        image: argonautcontainerregistry.azurecr.io/siop:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_BASE
          value: "https://dev.c19.cards/api"
---
apiVersion: v1
kind: Service
metadata:
  namespace: siop
  name: siop-sansdid
spec:
  selector:
    app: siop-sansdid
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: siop
  name: siop-sansdid
  labels:
    app: siop-sansdid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siop-sansdid
  template:
    metadata:
      labels:
        app: siop-sansdid
    spec:
      volumes:
      containers:
      - name: ui-sansdid
        image: argonautcontainerregistry.azurecr.io/siop:sansdid
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_BASE
          value: "https://sansdid.c19.cards/api"
